name: fan-out-s3
description: Fan-out pipeline with file, Kafka, and S3 destinations
type: pipeline
namespace: default
labels:
  pattern: fan-out
  step: "3"

config:
  input:
    http_server:
      address: 0.0.0.0:8080
      path: /events

  output:
    broker:
      pattern: fan_out
      outputs:
        # Local file for debugging
        - file:
            path: /tmp/events.jsonl
            codec: lines

        # Kafka for real-time streaming
        - kafka:
            addresses: ["${KAFKA_BROKERS}"]
            topic: sensor-events
            key: "${!this.sensor_id}"

        # S3 for long-term archival
        - aws_s3:
            bucket: "${S3_BUCKET}"
            region: "${AWS_REGION}"
            path: "events/${!timestamp_unix()}/${!uuid_v4()}.json"
            batching:
              count: 10
              period: 10s
