#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
Build and check the Claude plugin in plugin/.

Generates plugin/skills/find-expanso-skill/references/proven-jobs.md from the
`proof` blocks in skills/jobs/*/skill.yaml, so the plugin never restates a
proof claim by hand, then checks the plugin against the directory's
pre-submission rules that can be checked offline.

Usage:
    uv run -s scripts/build-plugin.py           # regenerate, then check
    uv run -s scripts/build-plugin.py --check   # fail on drift or a finding
"""

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugin"
JOBS = ROOT / "skills" / "jobs"
REPO_BLOB = "https://github.com/expanso-io/skills.expanso.io/blob/main"
PROVEN = PLUGIN / "skills" / "find-expanso-skill" / "references" / "proven-jobs.md"

NAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]{0,62}[a-z0-9])?$")
MAX_TEXT_BYTES = 256 * 1024
MAX_FILES = 512
SYSTEM_FILES = {".DS_Store", "Thumbs.db", "desktop.ini", "__MACOSX"}
STATUS_TEXT = {
    "executed-cloud-and-local": "Expanso Cloud and a local-mode node",
    "executed-local-only": "a local-mode node only, never through Cloud",
}


def render_proven_jobs() -> str:
    specs = [yaml.safe_load(p.read_text()) for p in sorted(JOBS.glob("*/skill.yaml"))]
    records = [(d.get("proof") or {}).get("record") for d in specs]
    records = [r for r in records if r]
    out = [
        "# Proven Expanso jobs",
        "",
        "Generated by `scripts/build-plugin.py` from the `proof` block in each",
        "`skills/jobs/<name>/skill.yaml`. Do not edit by hand.",
        "",
        "Each job below ran end to end with its output counted at the",
        "destination. Dated run records:",
        *sorted({f"<{REPO_BLOB}/{r}>" for r in records}),
        "Files are published at `https://skills.expanso.io/<name>/`, and each",
        "job's `README.md` there lists its dependency setup and output checks.",
        "",
        "Tell the user where a job was proven and read out its **Not proved**",
        "list before they rely on it.",
    ]
    for data in specs:
        proof = data.get("proof") or {}
        deps = data.get("dependencies") or {}
        comps = data.get("components") or {}
        status = proof.get("status", "unknown")
        out += ["", f"## {data['name']}", "", f"**Use it for:** {data.get('job', '')}", ""]
        out.append(
            f"**Proven on:** {STATUS_TEXT.get(status, status)}, "
            f"{proof.get('date', '?')}, expanso-edge {proof.get('expanso_edge', '?')}."
        )
        out.append("")
        out.append(f"**Job specs:** {', '.join(f'`{s}`' for s in data.get('job_specs', []))}")
        out.append("")
        parts = [f"{k}: {', '.join(v)}" for k, v in comps.items() if v]
        out.append(f"**Components:** {'; '.join(parts)}")
        out.append("")
        leaving = deps.get("data_leaving_host") or []
        if leaving:
            sent = "; ".join(f"{d['what']} to {d['to']}" for d in leaving)
        else:
            sent = "nothing beyond the node"
        out.append(f"**Sends:** {sent}.")
        out += ["", "**Proved:**", ""]
        out += [f"- {line}" for line in proof.get("proved", [])]
        out += ["", "**Not proved:**", ""]
        out += [f"- {line}" for line in proof.get("not_proved", [])]
    return "\n".join(out) + "\n"


def frontmatter(path: Path) -> dict | None:
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    return yaml.safe_load(m.group(1))


def readme_words(path: Path) -> int:
    text = re.sub(r"```.*?```", "", path.read_text(), flags=re.S)
    return len(re.findall(r"\b\w+\b", text))


def check() -> list[str]:
    errors: list[str] = []
    manifest = json.loads((PLUGIN / ".claude-plugin" / "plugin.json").read_text())
    name = manifest.get("name", "")
    if not NAME_RE.match(name):
        errors.append(f"plugin.json name {name!r} is not lowercase-hyphenated")
    for key in ("description", "author", "version", "license"):
        if key not in manifest:
            errors.append(f"plugin.json has no {key}")

    readme = PLUGIN / "README.md"
    if not readme.exists() or readme_words(readme) < 40:
        errors.append("plugin/README.md missing or under 40 words outside code blocks")
    if not (PLUGIN / "LICENSE").exists() and "license" not in manifest:
        errors.append("plugin has neither LICENSE nor a license field")

    files = [p for p in PLUGIN.rglob("*") if p.is_file()]
    if len(files) > MAX_FILES:
        errors.append(f"plugin has {len(files)} files, over {MAX_FILES}")
    for p in PLUGIN.rglob("*"):
        rel = p.relative_to(ROOT)
        if p.name in SYSTEM_FILES:
            errors.append(f"{rel}: system file")
        if p.is_symlink():
            errors.append(f"{rel}: symbolic link")
        if p.is_file() and p.stat().st_size > MAX_TEXT_BYTES:
            errors.append(f"{rel}: over 256 KiB")

    for skill_md in sorted((PLUGIN / "skills").glob("*/SKILL.md")):
        fm = frontmatter(skill_md)
        rel = skill_md.relative_to(ROOT)
        if fm is None:
            errors.append(f"{rel}: no YAML frontmatter")
            continue
        if fm.get("name") != skill_md.parent.name:
            errors.append(f"{rel}: name {fm.get('name')!r} != folder {skill_md.parent.name!r}")
        desc = fm.get("description")
        if not isinstance(desc, str) or not desc or len(desc) > 1024:
            errors.append(f"{rel}: description missing, not text, or over 1024 chars")
        if len(skill_md.read_text().splitlines()) > 500:
            errors.append(f"{rel}: over 500 lines")
        body = skill_md.read_text()
        for ref in re.findall(r"`((?:references|assets|scripts)/[^`\s]+)`", body):
            if not (skill_md.parent / ref).exists():
                errors.append(f"{rel}: references missing file {ref}")

    for cmd in sorted((PLUGIN / "commands").glob("*.md")):
        fm = frontmatter(cmd)
        if not fm or not isinstance(fm.get("description"), str):
            errors.append(f"{cmd.relative_to(ROOT)}: no text description in frontmatter")

    market = ROOT / ".claude-plugin" / "marketplace.json"
    if market.exists():
        entries = json.loads(market.read_text()).get("plugins", [])
        if not any(e.get("name") == name and e.get("source") == "./plugin" for e in entries):
            errors.append("marketplace.json has no entry for ./plugin under the plugin's name")
    return errors


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = ap.parse_args()

    rendered = render_proven_jobs()
    errors: list[str] = []
    if args.check:
        if not PROVEN.exists() or PROVEN.read_text() != rendered:
            errors.append(f"{PROVEN.relative_to(ROOT)} is stale; run scripts/build-plugin.py")
    else:
        PROVEN.parent.mkdir(parents=True, exist_ok=True)
        PROVEN.write_text(rendered)
        print(f"wrote {PROVEN.relative_to(ROOT)}")

    errors += check()
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    if not errors:
        print("plugin checks passed")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
